package sdn

import (
	"context"
	"fmt"
	"log"
	"sort"
	"sync"
	"time"
)

// RuleSet is the computed set of kernel rules for one node.
// Generated by the controller from the topology and distributed to nodes.
type RuleSet struct {
	NodeID       string         `json:"node_id"`
	TopologyHash string         `json:"topology_hash"`
	Version      uint64         `json:"version"`
	Rules        []*KernelRule  `json:"rules"`
	QoSBands     []*QoSBand     `json:"qos_bands"`
	Routes       []*KernelRoute `json:"routes"`
	ComputedAt   time.Time      `json:"computed_at"`
}

// KernelRule is a single firewall/routing rule ready for kernel application.
// Platform-specific data planes translate this into iptables, nftables,
// pf rules, or WFP filters.
type KernelRule struct {
	ID         string     `json:"id"`
	Priority   int        `json:"priority"`
	Action     RuleAction `json:"action"`
	Match      RuleMatch  `json:"match"`
	PolicyName string     `json:"policy_name"` // for audit trail
}

// RuleAction is what happens when a packet matches.
type RuleAction int

const (
	ActionAllow RuleAction = iota
	ActionDeny
	ActionRedirect
	ActionShape // apply QoS, then allow
)

// RuleMatch defines the packet matching criteria for a kernel rule.
type RuleMatch struct {
	SrcCIDRs []string `json:"src_cidrs"`
	DstCIDRs []string `json:"dst_cidrs"`
	DstHosts []string `json:"dst_hosts"` // resolved to IPs at application time
	SrcPorts []int    `json:"src_ports"`
	DstPorts []int    `json:"dst_ports"`
	Protocol string   `json:"protocol"` // "tcp" | "udp" | "icmp" | "" (any)
}

// QoSBand defines a traffic shaping band for a node interface.
type QoSBand struct {
	ID         string    `json:"id"`
	Priority   int       `json:"priority"`
	MaxBps     int64     `json:"max_bps"`
	GuarantBps int64     `json:"guarant_bps"`
	BurstBps   int64     `json:"burst_bps"`
	Match      RuleMatch `json:"match"`
}

// KernelRoute is a routing table entry.
type KernelRoute struct {
	Dst     string `json:"dst"`     // CIDR
	Gateway string `json:"gateway"` // IP or "" for direct
	Metric  int    `json:"metric"`
	Dev     string `json:"dev"` // interface name, "" = auto
}

// Controller is the SDN control plane.
// Runs on the coordinator node. Computes RuleSets and distributes them.
type Controller struct {
	mu          sync.RWMutex
	topology    *Topology
	nodeInfo    map[string]*NodeInfo // nodeID → info
	ruleSets    map[string]*RuleSet  // nodeID → current rule set
	distributor *Distributor
	reconciler  *Reconciler
	versions    *VersionStore
	clusterID   string
	ruleVersion uint64
}

// NodeInfo holds the current network state of a cluster node.
type NodeInfo struct {
	NodeID   string    `json:"node_id"`
	Hostname string    `json:"hostname"`
	Addrs    []string  `json:"addrs"`   // all IP addresses on the node
	Segment  string    `json:"segment"` // current segment assignment
	Online   bool      `json:"online"`
	LastSeen time.Time `json:"last_seen"`
}

// NewController creates an SDN controller.
func NewController(
	clusterID string,
	distributor *Distributor,
	reconciler *Reconciler,
	versions *VersionStore,
) *Controller {
	return &Controller{
		clusterID:   clusterID,
		nodeInfo:    make(map[string]*NodeInfo),
		ruleSets:    make(map[string]*RuleSet),
		distributor: distributor,
		reconciler:  reconciler,
		versions:    versions,
	}
}

// Apply installs a new topology. Computes rule sets for all nodes,
// distributes them via gossip, and waits for confirmation.
func (c *Controller) Apply(ctx context.Context, t *Topology) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	log.Printf("[sdn] applying topology %q (hash=%s)", t.Name, t.hash[:8])

	// Save current topology to version store for rollback
	if c.topology != nil {
		if err := c.versions.Save(c.topology); err != nil {
			log.Printf("[sdn] warn: could not save previous topology for rollback: %v", err)
		}
	}

	c.topology = t
	c.ruleVersion++

	// Compute rule sets for all known nodes
	ruleSets, err := c.computeAllRuleSets()
	if err != nil {
		return fmt.Errorf("compute rule sets: %w", err)
	}

	// Distribute to all nodes
	if err := c.distributor.Distribute(ctx, ruleSets); err != nil {
		return fmt.Errorf("distribute rule sets: %w", err)
	}

	// Store for reconciliation
	for nodeID, rs := range ruleSets {
		c.ruleSets[nodeID] = rs
	}

	log.Printf("[sdn] topology applied - %d nodes, %d total rules",
		len(ruleSets), c.totalRules(ruleSets))
	return nil
}

// computeAllRuleSets generates a RuleSet for every known node.
func (c *Controller) computeAllRuleSets() (map[string]*RuleSet, error) {
	result := make(map[string]*RuleSet, len(c.nodeInfo))
	for nodeID, info := range c.nodeInfo {
		if !info.Online {
			continue
		}
		rs, err := c.computeRuleSet(info)
		if err != nil {
			return nil, fmt.Errorf("node %s: %w", nodeID, err)
		}
		result[nodeID] = rs
	}
	return result, nil
}

// computeRuleSet generates the complete kernel rule set for one node.
func (c *Controller) computeRuleSet(node *NodeInfo) (*RuleSet, error) {
	rs := &RuleSet{
		NodeID:       node.NodeID,
		TopologyHash: c.topology.hash,
		Version:      c.ruleVersion,
		ComputedAt:   time.Now(),
	}

	nodeSeg := c.topology.SegmentForNode(node.NodeID)

	// Step 1: Generate segment isolation rules
	segRules := c.computeSegmentRules(nodeSeg, node)
	rs.Rules = append(rs.Rules, segRules...)

	// Step 2: Generate policy rules (user-defined, override segment defaults)
	policyRules := c.computePolicyRules(nodeSeg, node)
	rs.Rules = append(rs.Rules, policyRules...)

	// Step 3: Always-allow rules for cluster management traffic
	mgmtRules := c.computeManagementRules()
	rs.Rules = append(rs.Rules, mgmtRules...)

	// Step 4: QoS bands
	rs.QoSBands = c.computeQoSBands(nodeSeg)

	// Step 5: Routes
	rs.Routes = c.computeRoutes(node)

	// Step 6: Sort by priority (lower number = applied first)
	sort.Slice(rs.Rules, func(i, j int) bool {
		return rs.Rules[i].Priority < rs.Rules[j].Priority
	})

	return rs, nil
}

// computeSegmentRules generates rules from segment-level settings.
func (c *Controller) computeSegmentRules(seg *Segment, node *NodeInfo) []*KernelRule {
	var rules []*KernelRule

	if seg == nil {
		// Node not in any segment: deny all traffic except management
		rules = append(rules, &KernelRule{
			ID:       "seg-default-deny",
			Priority: 900,
			Action:   ActionDeny,
			Match:    RuleMatch{},
		})
		return rules
	}

	// Internet access
	if seg.Internet == "deny" {
		rules = append(rules, &KernelRule{
			ID:       fmt.Sprintf("seg-%s-deny-internet", seg.Name),
			Priority: 500,
			Action:   ActionDeny,
			Match: RuleMatch{
				DstCIDRs: publicInternetCIDRs(),
			},
			PolicyName: "segment:" + seg.Name,
		})
	}

	// Inter-segment traffic
	if seg.InterSegment == "deny" {
		for _, other := range c.topology.Segments {
			if other.Name == seg.Name {
				continue
			}
			if other.cidr == nil {
				continue
			}
			rules = append(rules, &KernelRule{
				ID:       fmt.Sprintf("seg-%s-deny-%s", seg.Name, other.Name),
				Priority: 400,
				Action:   ActionDeny,
				Match: RuleMatch{
					DstCIDRs: []string{other.cidr.String()},
				},
				PolicyName: "segment:" + seg.Name,
			})
		}
	}

	// Cluster access control
	if seg.ClusterAccess == "deny" {
		rules = append(rules, &KernelRule{
			ID:       fmt.Sprintf("seg-%s-deny-cluster", seg.Name),
			Priority: 300,
			Action:   ActionDeny,
			Match: RuleMatch{
				DstPorts: []int{4892, 4893, 11434},
			},
			PolicyName: "segment:" + seg.Name,
		})
	}

	return rules
}

// computePolicyRules converts user-defined policies to kernel rules.
func (c *Controller) computePolicyRules(nodeSeg *Segment, node *NodeInfo) []*KernelRule {
	var rules []*KernelRule

	for _, p := range c.topology.Policies {
		// Check if this policy applies to the node's segment
		if len(p.ApplyTo) > 0 && nodeSeg != nil {
			applies := false
			for _, s := range p.ApplyTo {
				if s == nodeSeg.Name {
					applies = true
					break
				}
			}
			if !applies {
				continue
			}
		}

		action := ActionAllow
		switch p.Action {
		case "deny":
			action = ActionDeny
		case "redirect":
			action = ActionRedirect
		case "allow":
			if p.QoS != nil {
				action = ActionShape
			}
		}

		rule := &KernelRule{
			ID:       "policy-" + p.Name,
			Priority: p.priority,
			Action:   action,
			Match: RuleMatch{
				DstHosts: p.Match.DstHost,
				SrcPorts: p.Match.SrcPort,
				DstPorts: p.Match.DstPort,
				Protocol: p.Match.Protocol,
				DstCIDRs: p.Match.DstCIDR,
			},
			PolicyName: p.Name,
		}
		rules = append(rules, rule)
	}
	return rules
}

// computeManagementRules generates always-allow rules for cluster traffic.
func (c *Controller) computeManagementRules() []*KernelRule {
	return []*KernelRule{
		{
			ID:       "mgmt-allow-fabric-api",
			Priority: 1,
			Action:   ActionAllow,
			Match: RuleMatch{
				DstPorts: []int{4892},
				Protocol: "tcp",
			},
			PolicyName: "management:fabric-api",
		},
		{
			ID:       "mgmt-allow-fabric-relay",
			Priority: 1,
			Action:   ActionAllow,
			Match: RuleMatch{
				DstPorts: []int{4893},
				Protocol: "tcp",
			},
			PolicyName: "management:fabric-relay",
		},
		{
			ID:       "mgmt-allow-mdns",
			Priority: 1,
			Action:   ActionAllow,
			Match: RuleMatch{
				DstPorts: []int{5353},
				Protocol: "udp",
			},
			PolicyName: "management:mdns",
		},
		{
			ID:         "mgmt-allow-established",
			Priority:   2,
			Action:     ActionAllow,
			Match:      RuleMatch{Protocol: "established"},
			PolicyName: "management:established",
		},
		{
			ID:       "mgmt-allow-loopback",
			Priority: 1,
			Action:   ActionAllow,
			Match: RuleMatch{
				DstCIDRs: []string{"127.0.0.0/8", "::1/128"},
			},
			PolicyName: "management:loopback",
		},
	}
}

// computeQoSBands generates traffic shaping bands for the node's interface.
func (c *Controller) computeQoSBands(seg *Segment) []*QoSBand {
	var bands []*QoSBand

	defaults := []struct {
		id       string
		priority int
		pct      float64
	}{
		{"critical", 1, 0.30},
		{"high", 2, 0.30},
		{"normal", 3, 0.30},
		{"low", 4, 0.10},
	}

	for _, d := range defaults {
		bands = append(bands, &QoSBand{
			ID:       d.id,
			Priority: d.priority,
		})
	}

	for _, p := range c.topology.Policies {
		if p.QoS == nil {
			continue
		}
		for i, band := range bands {
			if band.Priority == p.QoS.tcPriority {
				bands[i].MaxBps = p.QoS.maxBps
				bands[i].BurstBps = p.QoS.burstBps
				bands[i].GuarantBps = p.QoS.guaranteeBps
				bands[i].Match = RuleMatch{
					DstPorts: p.Match.DstPort,
					SrcPorts: p.Match.SrcPort,
					Protocol: p.Match.Protocol,
				}
			}
		}
	}

	if seg != nil && seg.bwBytes > 0 {
		for _, band := range bands {
			if band.MaxBps == 0 || band.MaxBps > seg.bwBytes {
				band.MaxBps = seg.bwBytes
			}
		}
	}

	return bands
}

// computeRoutes generates routing table entries for the node.
func (c *Controller) computeRoutes(node *NodeInfo) []*KernelRoute {
	var routes []*KernelRoute
	if c.topology == nil {
		return nil
	}
	for _, r := range c.topology.Routes {
		kr := &KernelRoute{
			Dst:    r.Dst,
			Metric: r.Metric,
		}
		switch r.Via {
		case "auto":
			kr.Gateway = ""
		case "tunnel":
			kr.Dev = "fabric0"
		default:
			kr.Gateway = r.Via
		}
		routes = append(routes, kr)
	}
	return routes
}

// UpdateNodeInfo updates the controller's knowledge of a node.
func (c *Controller) UpdateNodeInfo(info *NodeInfo) {
	c.mu.Lock()
	c.nodeInfo[info.NodeID] = info
	c.mu.Unlock()
}

// totalRules counts total rules across all node rule sets.
func (c *Controller) totalRules(sets map[string]*RuleSet) int {
	total := 0
	for _, rs := range sets {
		total += len(rs.Rules)
	}
	return total
}

// publicInternetCIDRs returns the CIDRs that are NOT private/RFC-1918.
func publicInternetCIDRs() []string {
	return []string{"0.0.0.0/0"}
}
