//go:build linux

package sdn

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// LinuxDataPlane implements the data plane on Linux using:
//   - nftables for firewall rules (replaces iptables, more efficient)
//   - tc (traffic control) for QoS/traffic shaping
//   - ip route for routing table management
type LinuxDataPlane struct {
	iface   string // primary network interface (e.g. "eth0", "wlan0")
	tableNS string // nftables table name for OpenFabric rules
}

// NewLinuxDataPlane creates a data plane for the given network interface.
func NewLinuxDataPlane(iface string) *LinuxDataPlane {
	if iface == "" {
		iface = detectPrimaryInterface()
	}
	return &LinuxDataPlane{
		iface:   iface,
		tableNS: "openfabric",
	}
}

// Apply atomically replaces all OpenFabric network rules with the given RuleSet.
func (d *LinuxDataPlane) Apply(rs *RuleSet) error {
	// Generate nftables ruleset
	nft := d.buildNftables(rs)

	// Write to temp file
	tmp, err := os.CreateTemp("", "fabric-nft-*.conf")
	if err != nil {
		return fmt.Errorf("create nft temp: %w", err)
	}
	defer os.Remove(tmp.Name())

	if _, err := tmp.WriteString(nft); err != nil {
		tmp.Close()
		return fmt.Errorf("write nft config: %w", err)
	}
	tmp.Close()

	// Atomic apply: nft -f applies the entire file as one transaction
	out, err := exec.Command("nft", "-f", tmp.Name()).CombinedOutput()
	if err != nil {
		return fmt.Errorf("nft apply: %s: %w", strings.TrimSpace(string(out)), err)
	}

	// Apply QoS using tc
	if err := d.applyQoS(rs.QoSBands); err != nil {
		return fmt.Errorf("apply QoS: %w", err)
	}

	// Apply routes
	if err := d.applyRoutes(rs.Routes); err != nil {
		return fmt.Errorf("apply routes: %w", err)
	}

	return nil
}

// buildNftables generates a complete nftables configuration from a RuleSet.
func (d *LinuxDataPlane) buildNftables(rs *RuleSet) string {
	var b strings.Builder

	// Flush existing OpenFabric table and recreate atomically
	fmt.Fprintf(&b, "table inet %s {\n", d.tableNS)
	fmt.Fprintf(&b, "  # Generated by OpenFabric SDN - do not edit manually\n")
	fmt.Fprintf(&b, "  # Topology hash: %s\n", rs.TopologyHash)
	fmt.Fprintf(&b, "  # Version: %d\n\n", rs.Version)

	// Input chain
	b.WriteString("  chain input {\n")
	b.WriteString("    type filter hook input priority filter; policy drop;\n")
	for _, rule := range rs.Rules {
		if nfRule := d.ruleToNft(rule, "input"); nfRule != "" {
			fmt.Fprintf(&b, "    %s\n", nfRule)
		}
	}
	b.WriteString("  }\n\n")

	// Forward chain
	b.WriteString("  chain forward {\n")
	b.WriteString("    type filter hook forward priority filter; policy drop;\n")
	for _, rule := range rs.Rules {
		if nfRule := d.ruleToNft(rule, "forward"); nfRule != "" {
			fmt.Fprintf(&b, "    %s\n", nfRule)
		}
	}
	b.WriteString("  }\n\n")

	// Output chain
	b.WriteString("  chain output {\n")
	b.WriteString("    type filter hook output priority filter; policy accept;\n")
	b.WriteString("  }\n")

	b.WriteString("}\n")

	// Prefix with flush to ensure atomic replace
	header := fmt.Sprintf("flush table inet %s\n", d.tableNS)
	return header + b.String()
}

// ruleToNft converts a KernelRule to an nftables rule string.
func (d *LinuxDataPlane) ruleToNft(rule *KernelRule, chain string) string {
	var parts []string

	// Protocol
	if rule.Match.Protocol != "" && rule.Match.Protocol != "established" {
		parts = append(parts, fmt.Sprintf("ip protocol %s", rule.Match.Protocol))
	}

	// Established connections
	if rule.Match.Protocol == "established" {
		return "ct state established,related accept"
	}

	// Source/Destination CIDRs
	for _, cidr := range rule.Match.SrcCIDRs {
		parts = append(parts, fmt.Sprintf("ip saddr %s", cidr))
	}
	for _, cidr := range rule.Match.DstCIDRs {
		if cidr == "0.0.0.0/0" {
			parts = append(parts, "ip daddr != { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8 }")
		} else {
			parts = append(parts, fmt.Sprintf("ip daddr %s", cidr))
		}
	}

	// Destination ports
	if len(rule.Match.DstPorts) == 1 {
		parts = append(parts, fmt.Sprintf("%s dport %d",
			nftProto(rule.Match.Protocol), rule.Match.DstPorts[0]))
	} else if len(rule.Match.DstPorts) > 1 {
		portList := make([]string, len(rule.Match.DstPorts))
		for i, p := range rule.Match.DstPorts {
			portList[i] = fmt.Sprintf("%d", p)
		}
		parts = append(parts, fmt.Sprintf("%s dport { %s }",
			nftProto(rule.Match.Protocol), strings.Join(portList, ", ")))
	}

	// Action
	var action string
	switch rule.Action {
	case ActionAllow, ActionShape:
		action = "accept"
	case ActionDeny:
		action = "drop"
	case ActionRedirect:
		action = "redirect"
	}

	if len(parts) == 0 && action == "accept" {
		return "accept"
	}
	if len(parts) == 0 && action == "drop" {
		return "drop"
	}

	comment := fmt.Sprintf("comment %q", rule.PolicyName)
	return strings.Join(append(parts, action, comment), " ")
}

// applyQoS installs tc (traffic control) rules for bandwidth shaping.
func (d *LinuxDataPlane) applyQoS(bands []*QoSBand) error {
	if len(bands) == 0 {
		return nil
	}

	// Remove existing qdisc
	_ = exec.Command("tc", "qdisc", "del", "dev", d.iface, "root").Run()

	// Get interface speed
	linkSpeedBps := d.getInterfaceSpeedBps()
	if linkSpeedBps == 0 {
		linkSpeedBps = 1000 * 1000 * 1000 // 1Gbps fallback
	}

	// Add root HTB qdisc
	out, err := exec.Command("tc", "qdisc", "add", "dev", d.iface,
		"root", "handle", "1:", "htb", "default", "30").CombinedOutput()
	if err != nil {
		return fmt.Errorf("add root qdisc: %s: %w", out, err)
	}

	// Add root class
	_ = exec.Command("tc", "class", "add", "dev", d.iface,
		"parent", "1:", "classid", "1:1",
		"htb", "rate", fmt.Sprintf("%dbps", linkSpeedBps)).Run()

	// Add per-band classes
	bandClasses := map[int]string{1: "10", 2: "20", 3: "30", 4: "40"}
	for _, band := range bands {
		classID := fmt.Sprintf("1:%s", bandClasses[band.Priority])

		// Calculate rate
		rateBps := int64(float64(linkSpeedBps) * 0.25)
		if band.GuarantBps > 0 {
			rateBps = band.GuarantBps
		}
		ceilBps := linkSpeedBps
		if band.MaxBps > 0 {
			ceilBps = band.MaxBps
		}
		burstBps := ceilBps / 10
		if band.BurstBps > 0 {
			burstBps = band.BurstBps
		}

		_ = exec.Command("tc", "class", "add", "dev", d.iface,
			"parent", "1:1", "classid", classID,
			"htb",
			"rate", fmt.Sprintf("%dbps", rateBps),
			"ceil", fmt.Sprintf("%dbps", ceilBps),
			"burst", fmt.Sprintf("%db", burstBps/8),
			"prio", fmt.Sprintf("%d", band.Priority),
		).Run()

		// Add SFQ leaf
		_ = exec.Command("tc", "qdisc", "add", "dev", d.iface,
			"parent", classID,
			"handle", fmt.Sprintf("%s0:", bandClasses[band.Priority]),
			"sfq", "perturb", "10").Run()

		// Add filter to classify traffic into this band
		if len(band.Match.DstPorts) > 0 {
			for _, port := range band.Match.DstPorts {
				proto := "tcp"
				if band.Match.Protocol == "udp" {
					proto = "udp"
				}
				_ = exec.Command("tc", "filter", "add", "dev", d.iface,
					"protocol", "ip",
					"parent", "1:0",
					"prio", fmt.Sprintf("%d", band.Priority),
					"u32",
					"match", proto, "dst", fmt.Sprintf("%d", port), "0xffff",
					"flowid", classID,
				).Run()
			}
		}
	}

	return nil
}

// applyRoutes installs routing table entries.
func (d *LinuxDataPlane) applyRoutes(routes []*KernelRoute) error {
	for _, r := range routes {
		var args []string

		if r.Dst == "0.0.0.0/0" || r.Dst == "::/0" {
			args = []string{"route", "replace", "default"}
		} else {
			args = []string{"route", "replace", r.Dst}
		}

		if r.Gateway != "" {
			args = append(args, "via", r.Gateway)
		}
		if r.Dev != "" {
			args = append(args, "dev", r.Dev)
		}
		if r.Metric > 0 {
			args = append(args, "metric", fmt.Sprintf("%d", r.Metric))
		}

		_ = exec.Command("ip", args...).Run()
	}
	return nil
}

// Flush removes all OpenFabric rules.
func (d *LinuxDataPlane) Flush() error {
	_ = exec.Command("nft", "delete", "table", "inet", d.tableNS).Run()
	_ = exec.Command("tc", "qdisc", "del", "dev", d.iface, "root").Run()
	return nil
}

// Status returns current rules.
func (d *LinuxDataPlane) Status() (string, error) {
	out, err := exec.Command("nft", "list", "table", "inet", d.tableNS).CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("nft list: %w", err)
	}
	return string(out), nil
}

// DataPlaneInterface returns the managed interface.
func (d *LinuxDataPlane) DataPlaneInterface() string {
	return d.iface
}

// detectPrimaryInterface finds the primary network interface.
func detectPrimaryInterface() string {
	out, err := exec.Command("ip", "route", "show", "default").Output()
	if err != nil {
		return "eth0"
	}
	fields := strings.Fields(string(out))
	for i, f := range fields {
		if f == "dev" && i+1 < len(fields) {
			return fields[i+1]
		}
	}
	return "eth0"
}

// getInterfaceSpeedBps reads the interface speed from sysfs.
func (d *LinuxDataPlane) getInterfaceSpeedBps() int64 {
	data, err := os.ReadFile(fmt.Sprintf("/sys/class/net/%s/speed", d.iface))
	if err != nil {
		return 0
	}
	var speedMbps int64
	fmt.Sscanf(strings.TrimSpace(string(data)), "%d", &speedMbps)
	return speedMbps * 1000 * 1000
}

// nftProto maps a protocol string to its nftables keyword.
func nftProto(proto string) string {
	switch strings.ToLower(proto) {
	case "udp":
		return "udp"
	case "tcp":
		return "tcp"
	default:
		return "tcp"
	}
}
